// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGet5OTAClJI_it5OI_-aH5XHa3TDgOPI',
    appId: '1:81073795834:web:2fa171ec6f8a8a331b0f43',
    messagingSenderId: '81073795834',
    projectId: 'flashchat-e7313',
    authDomain: 'flashchat-e7313.firebaseapp.com',
    databaseURL:
        'https://flashchat-e7313-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flashchat-e7313.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7S2KmlxPA9hAbICc0LX4Z43-oQ3B52Bg',
    appId: '1:81073795834:android:2658080338d856b21b0f43',
    messagingSenderId: '81073795834',
    projectId: 'flashchat-e7313',
    databaseURL:
        'https://flashchat-e7313-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flashchat-e7313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuTMb9UWv2s3D6bf3WLXHFCo1DNnxcGio',
    appId: '1:81073795834:ios:3749d47783c01c071b0f43',
    messagingSenderId: '81073795834',
    projectId: 'flashchat-e7313',
    databaseURL:
        'https://flashchat-e7313-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flashchat-e7313.appspot.com',
    iosBundleId: 'com.example.flashchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuTMb9UWv2s3D6bf3WLXHFCo1DNnxcGio',
    appId: '1:81073795834:ios:3749d47783c01c071b0f43',
    messagingSenderId: '81073795834',
    projectId: 'flashchat-e7313',
    databaseURL:
        'https://flashchat-e7313-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flashchat-e7313.appspot.com',
    iosBundleId: 'com.example.flashchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGet5OTAClJI_it5OI_-aH5XHa3TDgOPI',
    appId: '1:81073795834:web:111de78a885404771b0f43',
    messagingSenderId: '81073795834',
    projectId: 'flashchat-e7313',
    authDomain: 'flashchat-e7313.firebaseapp.com',
    databaseURL:
        'https://flashchat-e7313-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flashchat-e7313.appspot.com',
  );
}
